### ISSUE TITLE
discrepency between decodePaymentRequest and parsePaymentRequest

### ISSUE THREAD

**Issue by nicolasburtey** [alexbosworth/invoices#4]
decodePaymentRequest return `{token: undefined}` for zero-amount invoice
parsePaymentRequest return `{token: 0}` for zero-amount invoice

it would probably make sense to make to return the same value (assuming those function are meant to be interchangeable)

**Comment by alexbosworth** [comment]
Yeah this is a tough one

I actually think there are also two distinct states to represent

If mtokens === '1' then 0 tokens might represent the rounded down value rather than no value
If mtokens === '0' then undefined tokens might represent that there is no specific value at all requested, it is null/undefined

Unfortunately this is messy and it comes from a legacy of not having mtokens originally even be present in the API response, so I will have to think about how to deal with it more nicely

**Comment by alexbosworth** [comment]
Pushed a change to convert undefined responses into '0' and 0
